from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)


async def generate_ai_prompt(server_data: dict[str, Any], statistics_data: dict[str, Any], permissions_data: dict[str, Any], channels_data: dict[str, Any], roles_data: list[dict[str, Any]], automod_data: dict[str, Any]) -> str:
    lines: list[str] = []
    _add_line(lines, "=" * 60)
    _add_line(lines, "AI AUDIT PROMPT - DISCORD SERVER ANALYSIS")
    _add_line(lines, "=" * 60)
    _add_line(lines, f"Server: {server_data.get('name', 'Unknown')}")
    _add_line(lines, f"ID: {server_data.get('id', 'Unknown')}")
    _add_line(lines, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}")
    _add_line(lines, "=" * 60)
    _add_line(lines)
    _add_line(lines, "You are a Discord server architecture and community management expert.")
    _add_line(lines, "Analyze the following exported Discord server data and provide a comprehensive audit.")
    _add_line(lines)
    _add_line(lines, "--- SERVER OVERVIEW ---")
    _add_line(lines, f"Name: {server_data.get('name', 'Unknown')}")
    _add_line(lines, f"Description: {server_data.get('description', 'Not set')}")
    _add_line(lines, f"Members: {statistics_data.get('total_members', 0)} (Humans: {statistics_data.get('total_humans', 0)}, Bots: {statistics_data.get('total_bots', 0)})")
    _add_line(lines, f"Channels: {statistics_data.get('total_channels', 0)} (Text: {statistics_data.get('text_channels', 0)}, Voice: {statistics_data.get('voice_channels', 0)}, Forum: {statistics_data.get('forum_channels', 0)}, Stage: {statistics_data.get('stage_channels', 0)})")
    _add_line(lines, f"Categories: {channels_data.get('total_categories', 0)}")
    _add_line(lines, f"Roles: {statistics_data.get('total_roles', 0)}")
    _add_line(lines, f"Boost Tier: {statistics_data.get('boost_tier', 0)} (Boosts: {statistics_data.get('boost_count', 0)})")
    _add_line(lines, f"Verification: {server_data.get('verification_level', 'Unknown')}")
    _add_line(lines, f"Community: {'Yes' if server_data.get('is_community', False) else 'No'}")
    _add_line(lines, f"AutoMod Rules: {automod_data.get('total_rules', 0)}")
    _add_line(lines)
    _add_line(lines, "--- ANALYSIS CATEGORIES ---")
    _add_line(lines)
    _add_line(lines, "Please evaluate and provide detailed feedback on:")
    _add_line(lines)
    _add_line(lines, "1. Server Organization")
    _add_line(lines, "   - Is the channel layout logical and intuitive?")
    _add_line(lines, "   - Are categories used effectively?")
    _add_line(lines, "   - Are there missing channel types or categories?")
    _add_line(lines, "   - Is naming consistent across channels?")
    _add_line(lines)
    _add_line(lines, "2. Moderation & Security")
    _add_line(lines, "   - Is the verification level appropriate?")
    _add_line(lines, "   - Are AutoMod rules sufficient?")
    _add_line(lines, "   - Are there enough moderation channels (audit-log, mod-discussion)?")
    _add_line(lines, "   - Is the explicit content filter set correctly?")
    _add_line(lines)
    _add_line(lines, "3. Role & Permission Hierarchy")
    _add_line(lines, "   - Is the role hierarchy well-structured?")
    _add_line(lines, "   - Are there redundant or unnecessary roles?")
    _add_line(lines, "   - Are Administrator permissions too widespread?")
    _add_line(lines, "   - Are permission overlaps or conflicts present?")
    _add_line(lines)
    _add_line(lines, "4. Community Engagement")
    _add_line(lines, "   - Are there channels for introductions, memes, off-topic?")
    _add_line(lines, "   - Are forum channels used for Q&A or discussions?")
    _add_line(lines, "   - Are stage events used for community gatherings?")
    _add_line(lines, "   - Is there a boost/perks system?")
    _add_line(lines)
    _add_line(lines, "5. Growth Opportunities")
    _add_line(lines, "   - What channels or features are missing?")
    _add_line(lines, "   - What automations could be added?")
    _add_line(lines, "   - What bots would benefit this server?")
    _add_line(lines, "   - How can the server improve discoverability?")
    _add_line(lines)
    _add_line(lines, "--- OUTPUT FORMAT ---")
    _add_line(lines)
    _add_line(lines, "Provide your analysis in the following sections:")
    _add_line(lines)
    _add_line(lines, "## Critical Issues")
    _add_line(lines, "- List high-priority problems that need immediate attention.")
    _add_line(lines)
    _add_line(lines, "## Important Improvements")
    _add_line(lines, "- List medium-priority improvements that enhance the server.")
    _add_line(lines)
    _add_line(lines, "## Optional Improvements")
    _add_line(lines, "- List nice-to-have enhancements.")
    _add_line(lines)
    _add_line(lines, "## Improved Channel Layout")
    _add_line(lines, "- Suggest an optimized channel structure with categories.")
    _add_line(lines)
    _add_line(lines, "## Improved Role Hierarchy")
    _add_line(lines, "- Suggest an optimized role structure.")
    _add_line(lines)
    _add_line(lines, "## Recommended Bots")
    _add_line(lines, "- Suggest 3-5 bots with specific use cases.")
    _add_line(lines)
    _add_line(lines, "## Community Growth Plan")
    _add_line(lines, "- Outline a step-by-step plan to grow the community.")
    _add_line(lines)
    _add_line(lines, "## Security Audit")
    _add_line(lines, "- Identify security vulnerabilities and recommend fixes.")
    _add_line(lines)
    _add_line(lines, "--- DATA FILES ---")
    _add_line(lines)
    _add_line(lines, "Refer to the following JSON files for detailed data:")
    _add_line(lines, "- server.json: Server metadata, settings, features")
    _add_line(lines, "- roles.json: Complete role list with permissions")
    _add_line(lines, "- channels.json: All channels with permission overwrites")
    _add_line(lines, "- members.json: Member list with roles")
    _add_line(lines, "- permissions.json: Permission matrix across roles")
    _add_line(lines, "- statistics.json: Server statistics")
    _add_line(lines, "- threads.json: Active and archived threads")
    _add_line(lines, "- emojis.json: Custom emoji list")
    _add_line(lines, "- stickers.json: Custom sticker list")
    _add_line(lines, "- automod.json: AutoMod rule configuration")
    _add_line(lines, "- bots.json: Bot accounts and webhooks")
    _add_line(lines, "- invites.json: Active invites")
    _add_line(lines)
    _add_line(lines, "=" * 60)
    _add_line(lines, "END OF AI PROMPT")
    _add_line(lines, "=" * 60)
    _add_line(lines)
    _add_line(lines, "Please provide your complete audit analysis.")

    return "\n".join(lines)


def _add_line(lines: list[str], content: str = "") -> None:
    lines.append(content)
