from __future__ import annotations

import logging
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Any

from exporter.utils import sanitize_filename

logger = logging.getLogger(__name__)


def create_zip(
    server_name: str,
    output_dir: Path,
    data: dict[str, Any],
    markdown_content: str,
    ai_summary_content: str,
    ai_prompt_content: str,
) -> Path:
    sanitized_name = sanitize_filename(server_name)
    date_str = datetime.utcnow().strftime("%Y-%m-%d")
    zip_filename = f"{sanitized_name}_{date_str}.zip"
    zip_path = output_dir / zip_filename

    output_dir.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        _add_json_to_zip(zf, "server.json", data.get("server"))
        _add_json_to_zip(zf, "roles.json", data.get("roles"))
        _add_json_to_zip(zf, "members.json", data.get("members"))
        _add_json_to_zip(zf, "channels.json", data.get("channels"))
        _add_json_to_zip(zf, "permissions.json", data.get("permissions"))
        _add_json_to_zip(zf, "statistics.json", data.get("statistics"))
        _add_json_to_zip(zf, "threads.json", data.get("threads"))
        _add_json_to_zip(zf, "emojis.json", data.get("emojis"))
        _add_json_to_zip(zf, "stickers.json", data.get("stickers"))
        _add_json_to_zip(zf, "voice.json", data.get("voice"))
        _add_json_to_zip(zf, "stage.json", data.get("stage"))
        _add_json_to_zip(zf, "forums.json", data.get("forums"))
        _add_json_to_zip(zf, "automod.json", data.get("automod"))
        _add_json_to_zip(zf, "bots.json", data.get("bots"))
        _add_json_to_zip(zf, "invites.json", data.get("invites"))

        zf.writestr("server.md", markdown_content)
        zf.writestr("ai_summary.txt", ai_summary_content)

        if ai_prompt_content:
            zf.writestr("ai_prompt.txt", ai_prompt_content)

        readme_content = _generate_readme_txt(server_name, data)
        zf.writestr("README.txt", readme_content)

    logger.info("Created ZIP archive: %s", zip_path)
    return zip_path


def _add_json_to_zip(zf: zipfile.ZipFile, filename: str, data: Any) -> None:
    if data is None:
        zf.writestr(filename, "null")
        return
    try:
        import orjson
        content = orjson.dumps(data, option=orjson.OPT_INDENT_2 | orjson.OPT_SERIALIZE_NUMPY | orjson.OPT_UTC_Z)
    except ImportError:
        import json
        content = json.dumps(data, indent=2, default=str, ensure_ascii=False).encode("utf-8")
    zf.writestr(filename, content)


def _generate_readme_txt(server_name: str, data: dict[str, Any]) -> str:
    server = data.get("server", {})
    stats = data.get("statistics", {})

    lines = [
        f"Discord Server Export - {server_name}",
        f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "=== Contents ===",
        "server.json       - Server metadata and settings",
        "roles.json        - Complete role hierarchy with permissions",
        "members.json      - Member list with roles and metadata",
        "channels.json     - All channels (text, voice, forum, stage) with permission overwrites",
        "permissions.json  - Permission matrix across all roles",
        "statistics.json   - Server statistics and metrics",
        "threads.json      - Active and archived threads",
        "emojis.json       - Custom emoji list",
        "stickers.json     - Custom sticker list",
        "voice.json        - Voice channel details",
        "stage.json        - Stage channel details",
        "forums.json       - Forum channel details with tags",
        "automod.json      - AutoMod rule configuration",
        "bots.json         - Bot accounts and webhooks",
        "invites.json      - Active invites",
        "server.md         - Human-readable Markdown report",
        "ai_summary.txt    - AI-ready summary with health score",
        "ai_prompt.txt     - LLM prompt for server audit",
        "",
        "=== Quick Stats ===",
        f"Members: {stats.get('total_members', 'N/A')}",
        f"Channels: {stats.get('total_channels', 'N/A')}",
        f"Roles: {stats.get('total_roles', 'N/A')}",
        f"Boost Tier: {stats.get('boost_tier', 'N/A')}",
        "",
        "Generated by Discord Server Exporter",
    ]
    return "\n".join(lines)
